const axios = require('axios');
const crypto = require('crypto');
require('dotenv').config();

const MERCHANT_ID = process.env.REMITA_MERCHANT_ID;
const API_KEY = process.env.REMITA_API_KEY;
const SERVICE_TYPE_ID = process.env.REMITA_SERVICE_TYPE_ID;
const BASE_URL = process.env.REMITA_BASE_URL;

// Set REMITA_MODE=live in .env once you have real, working Remita merchant credentials.
// Until then, every RRR is simulated locally so payments never break due to Remita's sandbox being unreachable.
const LIVE_MODE = process.env.REMITA_MODE === 'live';

function simulateRRR({ amount, payerName, payerEmail, payerPhone, description }) {
  const rrr = 'SIM' + Math.floor(1000000000 + Math.random() * 8999999999);
  return { RRR: rrr, statusmessage: 'Simulated RRR generated successfully' };
}

function simulateStatus(rrr) {
  // Any RRR generated by this system is treated as immediately confirmable in simulation mode.
  return { status: '00', statusmessage: 'Simulated payment confirmed' };
}

async function generateRemitaRRR({ amount, payerName, payerEmail, payerPhone, description }) {
  if (!LIVE_MODE) {
    return simulateRRR({ amount, payerName, payerEmail, payerPhone, description });
  }

  const orderId = Date.now().toString();
  const hashInput = `${MERCHANT_ID}${SERVICE_TYPE_ID}${orderId}${amount}${API_KEY}`;
  const apiHash = crypto.createHash('sha512').update(hashInput).digest('hex');
  const url = `${BASE_URL}/echannelsvc/${MERCHANT_ID}/${SERVICE_TYPE_ID}/${apiHash}/api/paymentinit`;

  const body = { serviceTypeId: SERVICE_TYPE_ID, amount: String(amount), orderId, payerName, payerEmail, payerPhone, description };

  const response = await axios.post(url, body, {
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36',
      Authorization: `remitaConsumerKey=${MERCHANT_ID},remitaConsumerToken=${apiHash}`
    },
    timeout: 15000
  });
  return response.data;
}

async function checkRemitaStatus(rrr) {
  if (!LIVE_MODE || rrr.startsWith('SIM')) {
    return simulateStatus(rrr);
  }

  const hashInput = `${rrr}${API_KEY}${MERCHANT_ID}`;
  const apiHash = crypto.createHash('sha512').update(hashInput).digest('hex');
  const url = `${BASE_URL}/echannelsvc/${MERCHANT_ID}/${rrr}/${apiHash}/status.reg`;

  const response = await axios.get(url, {
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36',
      Authorization: `remitaConsumerKey=${MERCHANT_ID},remitaConsumerToken=${apiHash}`
    },
    timeout: 15000
  });
  return response.data;
}

module.exports = { generateRemitaRRR, checkRemitaStatus };